### PR TITLE
arm32: slp_switch should save r10

### PR DESCRIPTION
**Pull request by feisuzhu**
Meh.

### CODE REVIEW

**Comment by snaury** [comment]
Thanks! I looked into `gcc/config/arm/arm.h` and indeed, `r10` is a callee saved register. But that makes me wonder why I didn't include it in 2011, when I was fixing the list of registers. One idea would be that I used android ndk for compilation testing back then, and maybe it used `-mapcs-stack-check`, could you please maybe check if it affects compilation?

**Comment by feisuzhu** [comment]
arm-linux-androideabi-gcc -DANDROID -mandroid -g -fno-omit-frame-pointer --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm

```
Dump of assembler code for function slp_switch:
   0x00236dd8 <+0>:	push	{r4, r5, r6, r7, r8, r9, r11, lr}
   0x00236ddc <+4>:	add	r11, sp, #28
   0x00236de0 <+8>:	sub	sp, sp, #8
   0x00236de4 <+12>:	mov	r0, r11
   0x00236de8 <+16>:	str	r0, [r11, #-32]
   0x00236dec <+20>:	mov	r4, sp
   0x00236df0 <+24>:	mov	r0, r4
   0x00236df4 <+28>:	bl	0x236cbc <slp_save_state>
   0x00236df8 <+32>:	cmp	r0, #0
   0x00236dfc <+36>:	bne	0x236e4c <slp_switch+116>
   0x00236e00 <+40>:	ldr	r3, [pc, #76]	; 0x236e54 <slp_switch+124>
   0x00236e04 <+44>:	add	r3, pc, r3
   0x00236e08 <+48>:	ldr	r2, [r3, #4]
   0x00236e0c <+52>:	ldr	r2, [r2, #8]
   0x00236e10 <+56>:	cmp	r2, #0
   0x00236e14 <+60>:	moveq	r0, #1
   0x00236e18 <+64>:	beq	0x236e44 <slp_switch+108>
   0x00236e1c <+68>:	ldr	r3, [r3, #4]
   0x00236e20 <+72>:	ldr	r3, [r3, #8]
   0x00236e24 <+76>:	rsb	r4, r4, r3
   0x00236e28 <+80>:	add	sp, sp, r4
   0x00236e2c <+84>:	add	r11, r11, r4
   0x00236e30 <+88>:	bl	0x2360bc <slp_restore_state>
   0x00236e34 <+92>:	ldr	r0, [r11, #-32]
   0x00236e38 <+96>:	mov	r11, r0
   0x00236e3c <+100>:	mov	r3, #0
   0x00236e40 <+104>:	mov	r0, r3
   0x00236e44 <+108>:	sub	sp, r11, #28
   0x00236e48 <+112>:	pop	{r4, r5, r6, r7, r8, r9, r11, pc}
```









arm-linux-androideabi-gcc -DANDROID -mandroid -g -fno-omit-frame-pointer **-mapcs-stack-check -mapcs-frame** --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm

```
Dump of assembler code for function slp_switch:
   0x0023dd4c <+0>:	mov	r12, sp
   0x0023dd50 <+4>:	push	{r4, r5, r6, r7, r8, r9, r11, r12, lr, pc}
   0x0023dd54 <+8>:	sub	r11, r12, #4
   0x0023dd58 <+12>:	sub	sp, sp, #8
   0x0023dd5c <+16>:	mov	r0, r11
   0x0023dd60 <+20>:	str	r0, [r11, #-40]	; 0x28
   0x0023dd64 <+24>:	mov	r4, sp
   0x0023dd68 <+28>:	mov	r0, r4
   0x0023dd6c <+32>:	bl	0x23dc2c <slp_save_state>
   0x0023dd70 <+36>:	cmp	r0, #0
   0x0023dd74 <+40>:	bne	0x23ddc4 <slp_switch+120>
   0x0023dd78 <+44>:	ldr	r3, [pc, #76]	; 0x23ddcc <slp_switch+128>
   0x0023dd7c <+48>:	add	r3, pc, r3
   0x0023dd80 <+52>:	ldr	r2, [r3, #4]
   0x0023dd84 <+56>:	ldr	r2, [r2, #8]
   0x0023dd88 <+60>:	cmp	r2, #0
   0x0023dd8c <+64>:	moveq	r0, #1
   0x0023dd90 <+68>:	beq	0x23ddbc <slp_switch+112>
   0x0023dd94 <+72>:	ldr	r3, [r3, #4]
   0x0023dd98 <+76>:	ldr	r3, [r3, #8]
   0x0023dd9c <+80>:	rsb	r4, r4, r3
   0x0023dda0 <+84>:	add	sp, sp, r4
   0x0023dda4 <+88>:	add	r11, r11, r4
   0x0023dda8 <+92>:	bl	0x23d010 <slp_restore_state>
   0x0023ddac <+96>:	ldr	r0, [r11, #-40]	; 0x28
   0x0023ddb0 <+100>:	mov	r11, r0
   0x0023ddb4 <+104>:	mov	r3, #0
   0x0023ddb8 <+108>:	mov	r0, r3
   0x0023ddbc <+112>:	sub	sp, r11, #36	; 0x24
   0x0023ddc0 <+116>:	ldm	sp, {r4, r5, r6, r7, r8, r9, r11, sp, pc}
```

**Comment by snaury** [comment]
Strange, I don't see r10 anywhere in your listings, but I'll accept for now anyway.

**Comment by feisuzhu** [comment]
Strange indeed.

Code above are compiled WITHOUT this patch.
Code with this patch but not **-mapcs-stack-check** will save r10,
Code with this patch and **-mapcs-stack-check** will not use r10 anywhere(in my case, whole python interpreter, with greenlet statically linked in).

With patch, with 'stack-check', code generated are identical with code without this patch.

With patch, no 'stack-check'
```
Dump of assembler code for function slp_switch:
   0x00236dd8 <+0>:	push	{r4, r5, r6, r7, r8, r9, r10, r11, lr}
   0x00236ddc <+4>:	add	r11, sp, #32
   0x00236de0 <+8>:	sub	sp, sp, #12
   0x00236de4 <+12>:	mov	r0, r11
   0x00236de8 <+16>:	str	r0, [r11, #-40]	; 0x28
   0x00236dec <+20>:	mov	r4, sp
   0x00236df0 <+24>:	mov	r0, r4
   0x00236df4 <+28>:	bl	0x236cbc <slp_save_state>
   0x00236df8 <+32>:	cmp	r0, #0
   0x00236dfc <+36>:	bne	0x236e4c <slp_switch+116>
   0x00236e00 <+40>:	ldr	r3, [pc, #76]	; 0x236e54 <slp_switch+124>
   0x00236e04 <+44>:	add	r3, pc, r3
   0x00236e08 <+48>:	ldr	r2, [r3, #4]
   0x00236e0c <+52>:	ldr	r2, [r2, #8]
   0x00236e10 <+56>:	cmp	r2, #0
   0x00236e14 <+60>:	moveq	r0, #1
   0x00236e18 <+64>:	beq	0x236e44 <slp_switch+108>
   0x00236e1c <+68>:	ldr	r3, [r3, #4]
   0x00236e20 <+72>:	ldr	r3, [r3, #8]
   0x00236e24 <+76>:	rsb	r4, r4, r3
   0x00236e28 <+80>:	add	sp, sp, r4
   0x00236e2c <+84>:	add	r11, r11, r4
   0x00236e30 <+88>:	bl	0x2360bc <slp_restore_state>
   0x00236e34 <+92>:	ldr	r0, [r11, #-40]	; 0x28
   0x00236e38 <+96>:	mov	r11, r0
   0x00236e3c <+100>:	mov	r3, #0
   0x00236e40 <+104>:	mov	r0, r3
   0x00236e44 <+108>:	sub	sp, r11, #32
   0x00236e48 <+112>:	pop	{r4, r5, r6, r7, r8, r9, r10, r11, pc}
```

**Comment by snaury** [comment]
Cool, that's what I wanted to know. With `stack-check` register `r10` seems to have a special `stack limit` role, I was worried code wouldn't compile at all, though compiling and not saving it is very weird.

**Pull request merged**
