### PR TITLE
Closes #305: Add Python 3.11 support

### LINKED ISSUE #305: Consider releasing a new greenlet 1.1.3 version compatible with Python 3.11
The current main branch is a new greenlet 2.0 version which has a different API than greenlet 1.x and is written in C++. Shipping greenlet 2.0 alpha in the future Fedora 37 scheduled for next October (2022) sounds risky. We (Fedora) would like to upgrade Python to Python 3.11 but keep greenlet 1.x.

Would you be open to consider releasing a new greenlet 1.1.3 version which would be compatible with Python 3.11?

We prepared a PR on top on the 1.1.2 version to add Python 3.11 support.

Python 3.11 final version is also scheduled next October (2022): https://peps.python.org/pep-0664/#schedule

See also the issue #303: "Schedule for a beta release of greenlet 2.0?"

### PR DESCRIPTION
**Pull request by vstinner**
* Add GREENLET_PY311 macro
* PyGreenlet structure:

  * Add 3 members for the "data stack": 'datastack_chunk',
    'datastack_top' and 'datastack_limit'.
  * Add 'current_frame' member.

* Rename CFrame to _PyCFrame
* tox.ini: Add py311 environment.

Changes partially backport from the master branch:
commit 63e1099acc3677e614532bea0fa2e1967b69125f.

Co-Authored-By: Miro Hrončok <miro@hroncok.cz>

### CODE REVIEW

**Comment by vstinner** [comment]
Sadly, creating a PR on the master branch is wrong: this PR is based on the ``1.1.2`` tag. If the #305 "
Consider releasing a new greenlet 1.1.3 version compatible with Python 3.11" request is accepted, a new ``1.x`` branch based on the ``1.1.2`` tag should be created: ``git switch -c 1.x 1.1.2 && git push origin HEAD``. Then I can update re-target this PR to the new ``1.x`` branch ;-)

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@vstinner Can you please create the new PR towards new branch? We really want to see greenlet ready for py311 ASAP.

**Comment by vstinner** [comment]
> @vstinner Can you please create the new PR towards new branch? We really want to see greenlet ready for py311 ASAP.

Which new branch? https://github.com/python-greenlet/greenlet/branches

**Comment by joerick** [comment]
I'd like to see this merged also. I believe the commands to set up the 1.x branch would be...

```bash
git branch 1.x 1.1.2
git push origin 1.x
```

**Comment by jamadden** [comment]
Thank you for this PR! It has been merged into `maint/1.1` and 1.1.3 has been released to PyPI.

**Comment by vstinner** [comment]
> Thank you for this PR! It has been merged into maint/1.1 and 1.1.3 has been released to PyPI.

Great! Thank to **you**!

**Pull request closed without merging**
