### PR TITLE
Declare support for Python 3.12 in trove classifiers

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by mgorny** [comment]
Is it supported though? Bug #368 suggests that it's broken.

**Comment by edgarrmondragon** [comment]
> Is it supported though? Bug #368 suggests that it's broken.

Right. I can confirm that's still present on the debug build of latest 3.12.

**Comment by jamadden** [comment]
In a debug build of Python, yes, they crash. But most people aren't using a debug build of Python.

**Comment by mgorny** [comment]
I don't understand why people don't use debug builds on CI. Don't they want to know about breakage that's not visible in release builds? (such as API violations)

**Pull request merged**
