### PR TITLE
Update greenlet.txt

### PR DESCRIPTION
**Pull request by nosahama**
Updated a small typo on the main documentation page, i just could not resist lol.

### CODE REVIEW

**Comment by jamadden** [comment]
Hi! I'm a native English speaker and I hope my opinion can be helpful here. 

I think the phrase "is a still more primitive notion" is acceptable English usage. It puts emphasis on the "still more" part. It may sound a bit formal or old-fashioned.

In contrast, the suggested change "is still a more primitive notion", while readable, doesn't really provide the desired emphasis. I personally feel like it doesn't really sound right either. Removing the "still" helps with the sound, but also loses the emphasis.

**Comment by nosahama** [comment]
> Hi! I'm a native English speaker and I hope my opinion can be helpful here.
> 
> I think the phrase "is a still more primitive notion" is acceptable English usage. It puts emphasis on the "still more" part. It may sound a bit formal or old-fashioned.
> 
> In contrast, the suggested change "is still a more primitive notion", while readable, doesn't really provide the desired emphasis. I personally feel like it doesn't really sound right either. Removing the "still" helps with the sound, but also loses the emphasis.

Hi, i totally agree with the point on emphasis, at first sight, it looked a bit weird, but it's also a very small and ideally unnecessary change, so if you feel it's cool, i can close the PR. ;-)

**Comment by jamadden** [comment]
> Hi, i totally agree with the point on emphasis, at first sight, it looked a bit weird, but it's also a very small and ideally unnecessary change, so if you feel it's cool, i can close the PR. ;-)

That'd be fine with me 😄 (I'm not a maintainer, just an active user.)

Thanks for your efforts improving greenlet!

**Comment by nosahama** [comment]
The changes were deemed as **unnecessary**. Closing the PR.

**Pull request closed without merging**
