### PR TITLE
Fix, stabilize and extend CI matrix

### PR DESCRIPTION
**Pull request by BengtOFFIS**
This might fix broken builds like this one:

https://travis-ci.org/python-greenlet/greenlet/jobs/646537217

### CODE REVIEW

**Comment by BengtOFFIS** [comment]
Sorry for the messy commits, but I had to give this a few iterations. This fixes the latest build errors in Travis and extends the jobs to more platforms, while we are at it. I think this is ready to be merged, now. Do you agree?

**Comment by BengtOFFIS** [comment]
See https://github.com/python-greenlet/greenlet/pull/158/files for a summary of my changes.

**Comment by snaury** [comment]
It's already been fixed in some other PR. The failing job you are referring to was from a very old commit, which I tagged for new windows builds, and failing linux builds didn't matter.

**Comment by snaury** [comment]
But having older python versions tested is actually very good, so I'm going to merge it. Thank you!

**Comment by Bengt** [comment]
Great! Thanks for merging this.

**Pull request merged**
