### PR TITLE
Update for Python 3.11 alpha 6

### PR DESCRIPTION
**Pull request by vstinner**
* CFame was renamed to _PyCFrame
* _interpreter_frame was renamed to _PyInterpreterFrame

### CODE REVIEW

**Comment by vstinner** [comment]
Python 3.11 alpha6 is not released yet, so I create a draft PR for now.

I don't understand how greenlet can be built using _PyCFrame and _PyInterpreterFrame types, with _PyInterpreterFrame being part of the Python internal C API, whereas greenlet doesn't including the Python internal C API.

Maybe C++ allows to create pointers to unknown types, but require the types to be defined to deference them.

**Comment by brandtbucher** [comment]
Is this ready to be undrafted, @vstinner?

**Comment by vstinner** [comment]
> Is this ready to be undrafted, @vstinner?

Right. Ready for review!

**Comment by vstinner** [comment]
This change is for the master branch. I don't know if gevent and eventlet already use it or are using the 1.x stable branch. Is a separated PR needed?

**Comment by jamadden** [comment]
I haven't forgotten this. It's just waiting on 3.11a6 being available on GitHub Actions.

**Comment by vstinner** [comment]
Right now, I only see 3.11a5: https://github.com/actions/python-versions/blob/main/versions-manifest.json

**Comment by ncoghlan** [comment]
Please don't merge this yet, as the API changes are not final: https://discuss.python.org/t/proposal-rename-pyinterpreterframe-struct-as-py-framedata/14213/7

**Comment by ncoghlan** [comment]
Don't worry about my previous comment - we'll make sure code that works against 3.11a6 keeps working until https://github.com/faster-cpython/ideas/issues/309 provides a proper public API for the relevant frame manipulation tasks (although feel free to chime in there on the public API that you'd *like* to see to avoid having to delve into frame object internals)

**Comment by brandtbucher** [comment]
It looks like `3.11.0-alpha.6` is available for GitHub actions now.

@vstinner, mind updating `.github/workflows/tests.yml` to use it instead of `3.11.0-alpha.4`?

**Comment by vstinner** [comment]
> @vstinner, mind updating .github/workflows/tests.yml to use it instead of 3.11.0-alpha.4?

Done.

**Comment by vstinner** [comment]
@jamadden: GitHub Action jobs are not triggered on this PR?

**Comment by jamadden** [comment]
Yeah, I saw that. I don't know why, except that the AppVeyor build had been stuck for something like 23 days. I've restarted things and am monitoring.

**Comment by vstinner** [comment]
Yesterday, GitHub was sick: https://www.githubstatus.com/

Maybe close/reopen my PR if GitHub Actions doesn't start? Or I can create a new PR if needd.

**Comment by jamadden** [comment]
Closing and re-opening did it.

Thanks!

**Comment by vstinner** [comment]
Thanks for the merge!

> Closing and re-opening did it.

Magic! Well, as I wrote, GitHub was sick last days.

**Pull request merged**
