### PR TITLE
Add support for SuperH

### LINKED ISSUE #166: SuperH/sh4 architecture unsupported
I'm seeing this error when building greenlet using buildroot's ci [here](http://autobuild.buildroot.net/results/cd7/cd748aa26fdabcef72a581e1fe26edac14d07d2d/build-end.log).
```
greenlet needs to be ported to this platform, or teached how to detect your compiler properly.
```
If supporting this architecture is not possible I can flag greenlet as incompatible but it would be ideal to add support.

### PR DESCRIPTION
**Pull request by glaubitz**
Fixes #166

### CODE REVIEW

**Comment by glaubitz** [comment]
This a tested and fixed version of #398 while keeping the original author.

**Comment by glaubitz** [comment]
Ping.

**Comment by glaubitz** [comment]
Any chance this could be reviewed now that there is activity in this project again? Thanks.

**Comment by jamadden** [comment]
Thank you, this has been merged through a different branch.

**Pull request closed without merging**
