### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Fixes software supply chain safety warnings like at the bottom right of
https://github.com/python-greenlet/greenlet/actions/runs/10376229051

* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

Also, Python 3.7 was already end-of-life when Apple Silicon was released so Python 3.7 is not supported on modern Macs.

### CODE REVIEW

**Comment by cclauss** [comment]
@EwoutH Your review, please.

**Review by EwoutH — APPROVED** [review]
Looks good!

**Comment by cclauss** [comment]
Do you know how to correct the Linux tests?

**Comment by EwoutH** [comment]
From reading the error, you might need to mark it as safe.
```
git config --global --add safe.directory /greenlet/.git
```
I think you can just add a step:
```yml
    - name: Configure Git safe directory
      run: git config --global --add safe.directory /greenlet/.git
```

**Comment by cclauss** [comment]
I did hack with that but was unsuccessful.  Will try again on a separate PR.

**Comment by cclauss** [comment]
Generated 
#421

**Pull request closed without merging**
